/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author anupbochare
 */
public class AdminDashboard extends javax.swing.JPanel {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();


    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAttractionsManagement = new javax.swing.JButton();
        btnTransportManagement = new javax.swing.JButton();
        btnEventManagement = new javax.swing.JButton();
        btnAnalytics = new javax.swing.JButton();
        btnHospitalityManagement = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnUserManagement = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        btnAttractionsManagement.setText("Manage Tour Guides");
        btnAttractionsManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttractionsManagementActionPerformed(evt);
            }
        });

        btnTransportManagement.setText("Manage Transport");
        btnTransportManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransportManagementActionPerformed(evt);
            }
        });

        btnEventManagement.setText("Manage Events");
        btnEventManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventManagementActionPerformed(evt);
            }
        });

        btnAnalytics.setText("View Analytics ");
        btnAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyticsActionPerformed(evt);
            }
        });

        btnHospitalityManagement.setText("Manage Hotels");
        btnHospitalityManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalityManagementActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnUserManagement.setText("User Management");
        btnUserManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserManagementActionPerformed(evt);
            }
        });

        lblTitle.setText("Welcome To Admin Dashboard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEventManagement)
                                .addGap(18, 18, 18)
                                .addComponent(btnAnalytics))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHospitalityManagement)
                                    .addComponent(btnAttractionsManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTransportManagement)
                                    .addComponent(btnUserManagement)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(lblTitle)))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnalytics, btnAttractionsManagement, btnEventManagement, btnHospitalityManagement, btnTransportManagement, btnUserManagement});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAttractionsManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTransportManagement))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUserManagement)
                            .addComponent(btnHospitalityManagement)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEventManagement)
                            .addComponent(btnAnalytics))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAnalytics, btnAttractionsManagement, btnEventManagement, btnHospitalityManagement, btnTransportManagement, btnUserManagement});

    }// </editor-fold>//GEN-END:initComponents

    private void btnAttractionsManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttractionsManagementActionPerformed
        Container container = this.getParent();
        container.removeAll();
        AttractionsManagementPanel attractionsPanel = new AttractionsManagementPanel();
        container.add(attractionsPanel);
        container.revalidate();
        container.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAttractionsManagementActionPerformed

    private void btnEventManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventManagementActionPerformed
     Container container = this.getParent();
        container.removeAll();
        container.add(new EventManagementPanel());
        container.revalidate();
        container.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_btnEventManagementActionPerformed

    private void btnHospitalityManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalityManagementActionPerformed
         Container container = this.getParent();
        container.removeAll();
        container.add(new HospitalityManagementPanel());
        container.revalidate();
        container.repaint();       // TODO add your handling code here:
    }//GEN-LAST:event_btnHospitalityManagementActionPerformed

    private void btnAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyticsActionPerformed
     Container container = this.getParent();
        container.removeAll();
        container.add(new AnalyticsDashboardPanel());
        container.revalidate();
        container.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnalyticsActionPerformed

    private void btnUserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserManagementActionPerformed
        Container container = this.getParent();
        container.removeAll();
        container.add(new UserManagementJPanel());
        container.revalidate();
        container.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserManagementActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

            // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnTransportManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransportManagementActionPerformed
        Container container = this.getParent();
        container.removeAll();
        container.add(new TransportManagementPanel());
        container.revalidate();
        container.repaint();       // TODO add your handling code here:
    }//GEN-LAST:event_btnTransportManagementActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalytics;
    private javax.swing.JButton btnAttractionsManagement;
    private javax.swing.JButton btnEventManagement;
    private javax.swing.JButton btnHospitalityManagement;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTransportManagement;
    private javax.swing.JButton btnUserManagement;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
